#!/bin/bash
#python pretrain.py --dataset tiny --shuffle --learning_rate 0.00001 --opt adamw --batch 50 --bos 2 --monitor 10 --generate 100 --save 1000 --alt lite-base --slow 0.000152415
python pretrain.py --dataset tiny --shuffle --learning_rate 0.01 --opt sgd --batch 50 --bos 2 --monitor 10 --generate 100 --save 1000 --alt lite-base --freeze --load checkpoint.pt.2025.09.17-17.31.20
#python generate.py --device cpu --load checkpoint.pt --alt lite-base --vis --cmap gray
#python chart.py --log log.2025.09.17-17.31.20
